### ISSUE TITLE
Complete code ... Question...

### ISSUE THREAD

**Issue by netwobble** [UltimateAngular/ngrx-store-effects-app#3]
Hey Todd, Great course !!  Im just trying to get the full end source content... 
Question ... does master contain the start of the seed?  then each subsequent chapter is the start of the chapter?

Is there a final branch with all code?  

thanks,
AJ

**Comment by toddmotto** [comment]
Thanks! Yes each video corresponds to a GitHub branch :) you can also find those in the readme before the app setup. 

@toddmotto
